name: pkgdown

on:
  push: { branches: [main, master] }

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: website
          extra-packages: |
            any::pkgdown
            local::.

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - uses: actions/upload-pages-artifact@v3
        # por padrão, este action pega a pasta "_site" gerada pelo build_site_github_pages

      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          preview: false
