name: R-CMD-check

on:
  push: { branches: [main, master] }
  pull_request: { branches: [main, master] }

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      NOT_CRAN: true
      _R_CHECK_SYSTEM_CLOCK_: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true    # resolve dependências mais rápido/estável

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
          extra-packages: |
            any::rcmdcheck
            local::.

      # Fallback defensivo (se o cache falhar)
      - name: Ensure rcmdcheck is installed
        run: Rscript -e 'if (!requireNamespace("rcmdcheck", quietly = TRUE)) install.packages("rcmdcheck")'

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual","--as-cran")'
          build-args: '--no-manual'
          error-on: 'warning'
          check-dir: 'check'

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
          if-no-files-found: warn
